/**
 * The TypeScript core must reproduce the Python engine: every scenario in
 * python_reference.json (generated by the Python solver) is re-solved here
 * and compared point by point.
 */
import { describe, expect, it } from "vitest";
import ref from "./fixtures/python_reference.json";
import {
  type CalcInputs,
  atRange,
  calculateSolution,
  dropMrad,
  trueBallisticCoefficient,
  trueMuzzleVelocity,
  buildDopeTable,
} from "../src/core";

type PyInputs = Record<string, unknown>;

function toInputs(p: PyInputs, targetRangeM: number): CalcInputs {
  const segs = p.bc_segments as number[][] | undefined;
  return {
    muzzleVelocityMps: p.muzzle_velocity_mps as number,
    bcG7: (p.bc_g7 as number | null) ?? null,
    bcG1: (p.bc_g1 as number | null) ?? null,
    massGrains: p.mass_grains as number,
    diameterIn: p.diameter_inches as number,
    zeroRangeM: p.zero_range_m as number,
    targetRangeM,
    temperatureC: p.temperature_c as number,
    pressureMbar: p.pressure_mbar as number,
    humidityPct: p.humidity_pct as number,
    altitudeM: p.altitude_m as number,
    windSpeedMps: p.wind_speed_mps as number,
    windDirectionDeg: p.wind_direction_deg as number,
    latitudeDeg: p.latitude_deg as number,
    azimuthDeg: p.azimuth_deg as number,
    bulletLengthIn: p.bullet_length_in as number,
    twistRateIn: p.twist_rate_inches as number,
    twistDirection: (p.twist_direction as "right" | "left") ?? "right",
    sightHeightMm: p.sight_height_mm as number,
    elevationAngleDeg: (p.elevation_angle_deg as number) ?? 0,
    cantAngleDeg: (p.cant_angle_deg as number) ?? 0,
    bcSegments: segs ? segs.map((s) => [s[0], s[1]] as const) : null,
    zeroTemperatureC: (p.zero_temperature_c as number) ?? null,
    zeroPressureMbar: (p.zero_pressure_mbar as number) ?? null,
    zeroHumidityPct: (p.zero_humidity_pct as number) ?? null,
  };
}

describe("TypeScript core vs Python reference", () => {
  for (const sc of ref.scenarios) {
    it(sc.name, () => {
      const sol = calculateSolution(toInputs(sc.inputs as PyInputs, sc.target_range_m));
      expect(sol.stabilityFactor).toBeCloseTo(sc.stability_factor, 6);
      expect(sol.aeroJumpMrad).toBeCloseTo(sc.aero_jump_mrad, 6);
      expect(sol.spinDriftM).toBeCloseTo(sc.spin_drift_m, 6);
      expect(sol.coriolisHorizontalM).toBeCloseTo(sc.coriolis_h_m, 8);
      expect(sol.coriolisVerticalM).toBeCloseTo(sc.coriolis_v_m, 8);
      for (const p of sc.points) {
        const q = atRange(sol, p.range_m)!;
        // 0.1 mm tolerance in position, 0.01 m/s in velocity, 0.1 ms in time
        expect(Math.abs(q.dropM - p.drop_m)).toBeLessThan(1e-4);
        expect(Math.abs(q.windageM - p.windage_m)).toBeLessThan(1e-4);
        expect(Math.abs(q.velocityMps - p.velocity_mps)).toBeLessThan(1e-2);
        expect(Math.abs(q.timeS - p.time_s)).toBeLessThan(1e-4);
        expect(Math.abs(q.mach - p.mach)).toBeLessThan(1e-4);
        expect(Math.abs(q.energyJ - p.energy_j)).toBeLessThan(0.5);
      }
    });
  }

  it("MV truing recovers the reference MV", () => {
    const base = toInputs(ref.scenarios[0].inputs as PyInputs, 600);
    const r = trueMuzzleVelocity(base, ref.truing_mv.observed_drop_mrad, ref.truing_mv.observed_range_m);
    expect(r.converged).toBe(true);
    expect(Math.abs(r.value - ref.truing_mv.expected_mv)).toBeLessThan(0.5);
  });

  it("BC truing recovers the reference BC", () => {
    const base = toInputs(ref.scenarios[0].inputs as PyInputs, 900);
    const r = trueBallisticCoefficient(base, ref.truing_bc.observed_drop_mrad, ref.truing_bc.observed_range_m);
    expect(r.converged).toBe(true);
    expect(Math.abs(r.value - ref.truing_bc.expected_bc)).toBeLessThan(0.002);
  });

  it("dope table samples the requested ranges", () => {
    const base = toInputs(ref.scenarios[0].inputs as PyInputs, 1000);
    const rows = buildDopeTable(base, [100, 200, 300, 500, 800]);
    expect(rows.map((r) => r.rangeM)).toEqual([100, 200, 300, 500, 800]);
    expect(Math.abs(rows[0].dropMrad)).toBeLessThan(0.1); // ~zero at 100 m (aero jump from the reference wind)
    expect(rows[4].dropMrad).toBeLessThan(rows[3].dropMrad); // more drop further out
    expect(rows[4].windMrad).toBeGreaterThan(0);
  });

  it("solves fast enough for live UI use", () => {
    const base = toInputs(ref.scenarios[0].inputs as PyInputs, 1000);
    const t0 = performance.now();
    for (let i = 0; i < 5; i++) calculateSolution(base);
    const ms = (performance.now() - t0) / 5;
    expect(ms).toBeLessThan(250);
    console.log(`avg solve to 1000 m: ${ms.toFixed(1)} ms; drop@1000 = ${dropMrad(atRange(calculateSolution(base), 1000)!).toFixed(3)} mrad`);
  });
});
